{
 "title": "LlamaParse BYOC Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "LlamaParse Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Parsing Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(llamaparse_job_being_processed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parsing Jobs Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(llamaparse_job_consumed_total{}[$__rate_interval]))",
     "legendFormat": "Job Consumption Rate"
    }
   ]
  },
  {
   "title": "Parsing Job Rate by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(llamaparse_done_total{}[$__rate_interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Parsing Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Parsing Pipeline Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_pipeline_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_pipeline_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_pipeline_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_pipeline_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "LLM Api Call Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_llm_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_llm_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_llm_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_llm_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Parsing Preprocessing Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_preprocessing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_preprocessing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_preprocessing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_preprocessing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "File Download Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Filestore Download Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_load_s3_file_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_load_s3_file_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_load_s3_file_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_load_s3_file_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "File Download From Url Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_download_from_url_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_download_from_url_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_download_from_url_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_download_from_url_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Multimodal Parsing Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Multimodal Parsing Total Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_multimodal_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_multimodal_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_multimodal_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_multimodal_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Multimodal LLM Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_multimodal_llm_calls_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_multimodal_llm_calls_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_multimodal_llm_calls_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_multimodal_llm_calls_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "OCR Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "OCR Total Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_ocr_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_ocr_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_ocr_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_ocr_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "OCR HTTP Service Latency (secs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(llamaparse_ocr_call_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(llamaparse_ocr_call_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(llamaparse_ocr_call_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(llamaparse_ocr_call_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}