{
 "title": "LlamaCloud BYOC Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "LlamaCloud Job Status Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(llamacloud_job_status_counter_total{}[$__rate_interval])) by (job_name, status)",
     "legendFormat": "{{job_name}}: {{status}}"
    }
   ]
  },
  { "title": "Backend HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "2xx HTTP Requests by Endpoint (5m), api",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(api_http_requests_total{handler!~\"none|/api/health|/docs\", status=~\"2..\"}[5m])) by (handler, method, status)",
     "legendFormat": "{{method}}: {{handler}} ({{status}})"
    }
   ]
  },
  {
   "title": "4xx HTTP Requests (5m), api",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(api_http_requests_total{handler!~\"none|/api/health|/docs\", status=~\"4..\"}[5m])) by (handler, method, status)",
     "legendFormat": "{{method}}: {{handler}} ({{status}})"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors, llamacloud-api ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(api_http_requests_total{status=~\"5..\", handler!~\"/api/health\"}[5m])) by (handler, method)",
     "legendFormat": "{{method}}: {{handler}}"
    }
   ]
  },
  {
   "title": "Backend Api Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(api_http_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_http_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_http_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_http_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Backend Api Highr Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(api_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Jobs Service HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "HTTP Requests by Endpoint (5m), jobs-service",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(job_service_http_requests_total{handler!~\"/api/health\", status=~\"2..\"}[5m])) by (handler, method, status)",
     "legendFormat": "{{method}}: {{handler}} ({{status}})"
    }
   ]
  },
  {
   "title": "HTTP 4xx errors, jobs-service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(job_service_http_requests_total{status=~\"4..\"}[5m])) by (handler, method, status)",
     "legendFormat": "{{method}}: {{handler}} ({{status}})"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors, jobs-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(job_service_http_requests_total{status=~\"5..\"}[5m])) by (handler, method, status)",
     "legendFormat": "{{method}}: {{handler}} ({{status}})"
    }
   ]
  },
  {
   "title": "Job Service Api Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(job_service_http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(job_service_http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(job_service_http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(job_service_http_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Job Service Higher Http Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(job_service_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(job_service_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(job_service_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(job_service_http_request_duration_highr_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}